server:
  port: 8081
spring:
  application:
    name: "schedule-reminder-system"
  logging:
    level:
      ROOT: DEBUG

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
          must-revalidate: true


  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

schedule:
  fixedRate: 1000000